config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index"

  get '/:short_key' => 'welcome#s_url', as: :s_url  
  get '/:short_key/admin'	=> 'welcome#admin', as: :admin
  get '/:short_key/block'	=> 'welcome#block', as: :block
  resources :welcome
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord

  enum state: {
    pending: 0,
    blocked: -10,
  }

  def s_url
  	url_helpers.s_url_url(self.short_key, host: 'http://localhost:3001')
  end

  def admin_url
  	url_helpers.admin_url(self.short_key, host: 'http://localhost:3001')
  end

	before_create do 		
		chars = [*'a'..'z',*'0'..'9',*'A'..'Z']
		hex = Digest::MD5.hexdigest(target)
		hex_len = hex.length
		sub_hex_len = hex_len / 8

		(0...sub_hex_len).each do |i|
			out_chars = ""
	   		j = i + 1
	   		sub_hex = hex[i * 8...j * 8]
	   		idx = 0x3FFFFFFF & sub_hex.to_i(16)
	   		(0...6).each do |i|
	   			index = 0x0000003D & idx
	   			out_chars += chars[index]
	   			idx = idx >> 5
	   		end	
	   	
	   	if !ShortUrl.find_by(short_key: out_chars)
	   		self.short_key = out_chars
	   		break
	   	end
		end
	end

	def url_helpers
		Rails.application.routes.url_helpers
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def render_not_found
		render :file => "/public/404.html", :status => 404
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :find_short_url, only: [:admin, :s_url, :block]

	def index
		gon.short_urls = ShortUrl.all.map{|short_url|
			set_gon(short_url)
		}
	end

	def create
		short_url = ShortUrl.new(short_url_params)
		short_url.save
		render json: set_gon(short_url)
	end


	def s_url
		if @short_url.blocked?
			render_not_found
		else
			@short_url.visits = @short_url.visits.to_i + 1
			@short_url.save

			redirect_to @short_url.target
		end
	end

	def admin		
	end

	def block
		@short_url.blocked!
		redirect_to root_path
	end

	private

	def find_short_url
		@short_url = ShortUrl.find_by(short_key: params[:short_key])
	end

	def short_url_params
		params.permit(:target)
	end

	def set_gon(short_url)
		short_url.as_json.merge(s_url: short_url.s_url, visits: short_url.visits.to_i, state: short_url.state, admin_url: short_url.admin_url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :assets%>
    <%= Gon::Base.render_data%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/admin.html.erb
<div>短地址: <%= @short_url.s_url%></div>
<div>访问地址: <%= @short_url.target%></div>
<div>状态: <%= @short_url.state%></div>
<%- if @short_url.pending?%>
	<%= link_to '禁止访问', block_path(@short_url.short_key), data: {confirm: '确定要禁止访问此网站吗'}, class: 'btn btn-danger'%>
<%- end%>

app/views/welcome/index.html.erb
<%= content_for :assets do %>
	<%= javascript_include_tag 'short_url.js'%>
<%- end%>
<div class="content clearfix">
	<h5>短域名</h5>
	<div class="list"></div>
	<form class="needs-validation">
		<div class="form-group ">
			<input type="text" name="new_target" class="form-control" placeholder="url地址" required="true">	
			<a class="mt-2 add btn btn-primary" href="javascript:;"  >添加短地址</a>
		</div>
	</form>

</div>



<script type="text/x-handlebars-template" id="urlView">
	<input type="text" name="target" class="form-control" value="{{target}}">	
	<div class="text-muted">
		短地址: 
		<a href="{{s_url}}" target="_blank">{{s_url}}</a>
	</div>
	<div class="text-muted">访问次数: {{visits}}</div>
	<div class="text-muted">
		管理页面:
		<a href="{{admin_url}}" target="_blank">{{admin_url}}</a>
	</div>
</script>